name: mlflow-examples
channels:
- defaults
dependencies:
- python=3.7.5
- pip:
    - mlflow==1.5.0
    - scikit-learn==0.20.3
    - matplotlib
    - pyarrow
    - xgboost==0.90
    - jupyter
    - mleap
    - boto3
