name: mlflow-examples-catboost
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip:
    - mlflow==1.8.0
    - catboost==0.22
    - scikit-learn==0.20.2
    - onnx==1.6.0
    - onnxmltools==1.6.1
    - onnxruntime==1.2.0
