name: mlflow-examples-catboost
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip:
    - mlflow==1.9.0
    - catboost==0.22
    - scikit-learn==0.20.2
    - pyarrow==0.12.1
    - onnx==1.7.0
    - onnxmltools==1.6.1
    - onnxruntime==1.3.0
