name: mlflow-examples-keras2-mnist
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip:
    - mlflow==1.8.0
    - tensorflow==2.2.0
    - onnx==1.6.0
    - onnxmltools==1.6.1
    - onnxruntime==1.2.0
