name: mlflow-examples-keras_tf2_mnist
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip:
    - mlflow==1.8.0
    - tensorflow==2.1.0
    - onnx==1.7.0
    - onnxmltools==1.6.1
    - onnxruntime==1.3.0
