name: mlflow-examples-sklearn
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip:
    - mlflow==1.9.0
    - click==7.1.2
    - scikit-learn==0.20.2
    - matplotlib==3.2.1
    - pyarrow==0.12.1
    - onnx==1.7.0
    - onnxmltools==1.6.1
    - onnxruntime==1.3.0
